[package]
name = "pizza-analysis-jieba"
version = "0.1.0"
edition = "2021"
description = "Jieba Chinese segmentation plugin for INFINI Pizza"
repository = "https://github.com/pizza-rs/analysis-jieba"
categories = ["text-processing"]
keywords = ["pizza", "jieba", "chinese", "tokenizer", "search"]
authors = ["INFINI Labs Team",]
license = "MIT"



[features]
default = []
std = ["pizza-engine/std"]

[dependencies]
pizza-common = { path = "../../lib/common" }
pizza-engine = { path = "../../lib/engine", default-features = false }

jieba-rs = { version = "0.7", features = ["tfidf", "textrank","default-dict"],default-features = false }
